language: python
python: "3.7"

jobs:
  include:
    - stage: "Native host build and tests"
      name: "Unit and database tests"
      services:
        - postgresql
      install:
        - pip install --quiet .
        - pip install --quiet -r dev-requirements.txt
      before_script:
        - psql -c "create user transiter with CREATEDB password 'transiter';" -U postgres
        - psql -c "create database transiter;" postgres -U transiter
      script:
        - coverage run -m pytest --color=yes tests/unit tests/db
      after_success:
        - pip install --quiet coveralls
        - coveralls

    - name: "End to end tests"
      services:
        - postgresql
      install:
        - pip install --quiet .
        - pip install --quiet -r dev-requirements.txt
      before_script:
        - psql -c "create user transiter with CREATEDB password 'transiter';" -U postgres
        - psql -c "create database transiter;" postgres -U transiter
        - docker run -d -p 5672:5672 rabbitmq:3
        - transiterclt db reset --yes
        - transiterclt launch webservice > webservice.log &
        - transiterclt launch executor > executor.log &
        - transiterclt launch scheduler > scheduler.log &
        - python tests/endtoend/sourceserver.py > sourceserver.log &
      script:
        - pytest --color=yes tests/endtoend

    - name: "Formatting enforcement"
      install:
        - pip install --quiet black==19.10b pycodestyle==2.5.0
      script:
        - black transiter tests *py
        - pycodestyle --ignore=E203,E501,W503 --exclude="*pb2.py" transiter tests *py

    - stage: "Docker build and tests"
      name: "Docker build (CPython 3.7)"
      install:
        - pip install --quiet docker
        - python travis.py before
        - make docker-ci
        - docker-compose -p transiter -f docker/docker-compose.yml up -d
      script:
        - make containerized-unit-tests
        - make containerized-db-tests
        - make end-to-end-tests
      after_success:
        - python travis.py after
