language: python
python: "3.7"
dist: trusty

jobs:
  include:
    - stage: "First"
      name: "Unit and database tests"
      services:
        - postgresql
      install:
        - pip install --quiet .
        - pip install --quiet -r dev-requirements.txt
      before_script:
        - psql -c "create user transiter with CREATEDB password 'transiter';" -U postgres
        - psql -c "create database transiter;" postgres -U transiter
      script:
        - coverage run -m pytest --color=yes tests/unit tests/db
      after_success:
        - pip install --quiet coveralls
        - coveralls

    - name: "End to end tests"
      services:
        - postgresql
        - rabbitmq
      addons:
        apt:
          packages:
            - rabbitmq-server
      install:
        - pip install --quiet .
        - pip install --quiet -r dev-requirements.txt
      before_script:
        - psql -c "create user transiter with CREATEDB password 'transiter';" -U postgres
        - psql -c "create database transiter;" postgres -U transiter
        - transiterclt launch webservice &
        - transiterclt launch executor &
        - transiterclt launch scheduler &
        - python tests/endtoend/sourceserver.py
      script:
        - pytest --color=yes tests/endtoend

    - name: "Formatting enforcement"
      install:
        - pip install --quiet black==19.10b pycodestyle==2.5.0
      script:
        - black transiter tests *py
        - pycodestyle --ignore=E203,E501,W503 --exclude="*pb2.py" transiter tests *py
