services:
  - postgresql
language: python
python: "3.5"
before_script:
- psql -c 'create database transiter_test_db;' -U postgres
- psql -c 'create database transiter_test_db_2;' -U postgres
install:
  - python setup.py install
  - pip install coveralls
# command to run tests
script:
  - pip install -r dev-requirements.txt
  - make unit-tests
  - TRANSITER_CONFIG=tests/integrationtest/transiter-config.toml make db-tests
  - make integration-tests
after_success:
  - coveralls
