# Python is used here just to install coveralls and docker. It is not necessary to
# keep the version in sync with Transiter's Python version.
language: python
python: "3.7"

jobs:
  include:
    - stage: "First"
      name: "Unit and database tests"
      services:
        - postgresql
      before_script:
        - psql -c "create user transiter with CREATEDB password 'transiter';" -U postgres
        - psql -c "create database 'transiter';" -U transiter
      install:
        - pip install --quiet .
        - pip install --quiet -r dev-requirements.txt
      script:
        - pytest tests/unit tests/db

    - name: "Formatting enforcement"
      install:
        - pip install --quiet black==19.10b pycodestyle==2.5.0
      script:
        - black transiter tests *py
        - pycodestyle --ignore=E203,E501,W503 --exclude="*pb2.py" transiter tests *py
