services:
  - postgresql
language: python
sudo: required
dist: xenial
python: "3.7"
before_script:
  - psql -c 'create database transiter_test_db;' -U postgres
install:
  - python setup.py install
  - pip install coveralls
# command to run tests
script:
  - pip install -r dev-requirements.txt
  - make integration-tests
  - make unit-tests
after_success:
  - coveralls
