# Python is used here just to install coveralls and docker. It is not necessary to
# keep the version in sync with Transiter's Python version.
language: python
python: "3.7"

jobs:
  include:
    - stage: "Native tests"
      name: "Build Docker image"
      script:
      - pip install --quiet docker
      - python travis.py before
      - make docker-ci
      - docker-compose -p transiter -f docker/docker-compose.yml up -d
      - make containerized-db-tests
    - name: "Unit and database tests"
      script:
        - pip install .
        - pip install -r dev-requirements.txt
        - pytest tests/unit
    - name: "Formatting enforcement"
      script:
        - pip install --queit black==19.10b pycodestyle==2.5.0
        - black transiter tests *py
        - pycodestyle --ignore=E203,E501,W503 --exclude="*pb2.py" transiter tests *py


