# Python is used here just to install coveralls and docker. It is not necessary to
# keep the version in sync with Transiter's Python version.
language: python
python: "3.6"

jobs:
  include:
    - stage: docker
      name: "Build Docker image"
      script:
      - pip install --quiet docker
      - python travis.py before
      - make docker-ci
      - docker-compose -p transiter -f docker/docker-compose.yml up -d
      - make containerized-unit-tests
    - name: "DB tests"
      script:
      - pip install --quiet docker
      - python travis.py before
      - make docker-ci
      - docker-compose -p transiter -f docker/docker-compose.yml up -d
      - make containerized-db-tests


