# Python is used here just to install coveralls and docker. It is not necessary to
# keep the version in sync with Transiter's Python version.
language: python
python: "3.6"

install:
  - pip install coveralls docker
  - docker-compose up -d --build

script:
  - make python-tests-in-docker-container
  - python tests/endtoend/dockerdriver.py

after_success:
  # The next command transforms paths in the .coverage file from being relative
  # to the Docker container to be relative to the Travis CI build directory. This
  # is necessary for correct coverage reporting.
  - coverage combine .coverage
  - coveralls
  - bash docker/docker_hub_push.sh
