version: '3.5'
# TODO: need to figure out what's happening with env variables
services:

  webserver:
    environment:
      - TRANSITER_TASKSERVER_HOST=taskserver
      - TRANSITER_TASKSERVER_PORT
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    image: jamespfennell/transiter:latest-webserver
    container_name: transiter-webserver
    env_file: .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: always

  taskserver:
    build:
      context: .
      dockerfile: docker/taskserver/Dockerfile
    image: jamespfennell/transiter:latest-taskserver
    env_file: .env
    expose:
      - "${TRANSITER_TASKSERVER_PORT:-5000}"
    restart: always

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    image: jamespfennell/transiter:latest-postgres
    volumes:
      - data-volume:/var/lib/postgresql/pata  # TODO: ?
    expose:
      - "${TRANSITER_DB_PORT:-5432}"
    restart: always

volumes:
  data-volume:

