

[database]

driver = "postgresql"
dialect = ""
host = "localhost"
port = 80
name = "transiter"
username = "transiter"
password = ""

[task_server]

port = 5000

[systems.nycsubway]

mta_api_key = ""
local_dir = "../transiter-nycsubway"