version: '3.5'

services:

  unit-tests:
    image: jamespfennell/transiter-ci:latest
    container_name: unit-tests
    command: unit-tests
    tty: true
    volumes:
      - ${PWD}/coverage:/transiter-ci/coverage

  db-tests:
    image: jamespfennell/transiter-ci:latest
    container_name: db-tests
    command: db-tests
    tty: true
    environment:
      - TRANSITER_DB_HOST=postgres-db-tests
      - TRANSITER_DB_PORT=5432
    volumes:
      - ${PWD}/coverage:/transiter-ci/coverage

  postgres-db-tests:
    image: postgres:12
    expose:
      - "5432"

