
apiVersion: v1

kind: Pod

metadata:
  name: {{ .Values.name }}-installer
  labels:
    app: {{ .Values.name }}
    provides: installer
spec:
  restartPolicy: Never
  containers:
  - name: {{ .Values.name }}-installer
    image: jamespfennell/transiter:{{ .Values.version }}
    command:
    - transiterclt
    - db
    - init
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: {{ .Values.name }}-config
