apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nginx
  labels:
    app: {{ .Values.name }}
    provides: proxy
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.name }}
    provides: proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-nginx
  labels:
    app: {{ .Values.name }}
    provides: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      service: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        provides: proxy
    spec:
      containers:
        - image: gcr.io/mta-music-318515/transiter-nginx:latest
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
