
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.name }}-postgres
  labels:
    app: {{ .Values.name }}-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-postgres-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-postgres-pod
    spec:
      containers:
      - name: {{ .Values.name }}-postgres
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: transiter
        - name: POSTGRES_PASSWORD
          value: transiter
        - name: POSTGRES_DB
          value: transiter
{{ if .Values.postgres.persistentVolume.enabled }}
        volumeMounts:
        - name: {{ .Values.name }}-postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: {{ .Values.name }}-postgres-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-postgres-pv-claim
{{ end }}

---

apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.name }}-postgres
  labels:
    app: {{ .Values.name }}-postgres

spec:
  ports:
  - name: psql
    port: 5432
    protocol: TCP
  selector:
    app: {{ .Values.name }}-postgres-pod


{{ if .Values.postgres.persistentVolume.enabled }}
---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.name }}-postgres-pv-claim
spec:
  storageClassName: {{ .Values.postgres.persistentVolume.storageClassName }}
  accessModes:
    - {{ .Values.postgres.persistentVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistentVolume.capacity }}

{{ end }}
