
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.name }}-rabbitmq
  labels:
    app: {{ .Values.name }}-rabbitmq

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-rabbitmq-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-rabbitmq-pod
    spec:
      containers:
      - name: {{ .Values.name }}-rabbitmq
        image: rabbitmq:3
        ports:
        - containerPort: 5672
        - containerPort: 15672

---

apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.name }}-rabbitmq
  labels:
    app: {{ .Values.name }}-rabbitmq

spec:
  ports:
  - name: http
    protocol: TCP
    port: 15672
  - name: amqp
    protocol: TCP
    port: 5672
  selector:
    app: {{ .Values.name }}-rabbitmq-pod


