
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.name }}-scheduler
  labels:
    app: {{ .Values.name }}
    provides: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      provides: scheduler
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        provides: scheduler
    spec:
      containers:
      - name: {{ .Values.name }}-scheduler
        image: jamespfennell/transiter:{{ .Values.version }}
        command:
        - gunicorn
        - -b
        - 0.0.0.0:80
        - -w
        - "1"
        - "transiter.scheduler.server:create_app()"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}-config
{{- if .Values.pythonPackagesToProvide }}
        lifecycle:
          postStart:
            exec:
              command:
                - "pip"
                - "install"
{{- range $index, $element := .Values.pythonPackagesToProvide }}
                - "{{ $element }}"
{{- end}}
{{- end }}

---

apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.name }}-scheduler
  labels:
    app: {{ .Values.name }}
    provides: scheduler

spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Values.name }}
    provides: scheduler
