
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.name }}-webservice
  labels:
    app: {{ .Values.name }}-webservice

spec:
  replicas: {{ .Values.webservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-webservice-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-webservice-pod
    spec:
      containers:
      - name: {{ .Values.name }}-webservice
        image: jamespfennell/transiter:{{ .Values.version }}-webserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        args: ["-w", "{{ .Values.webservice.workersPerReplica }}", "-t", "{{ .Values.webservice.timeout }}"]
        env:
        - name: TRANSITER_TASKSERVER_HOST
          value: "{{ .Values.name }}-taskserver"
        - name: TRANSITER_TASKSERVER_PORT
          value: "18812"
        - name: TRANSITER_DB_HOST
          value: "{{ .Values.name }}-postgres"
        - name: TRANSITER_DB_PORT
          value: "5432"
        {{ if .Values.documentationEnabled }}
        - name: TRANSITER_DOCUMENTATION_ENABLED
          value: "true"
        {{ end }}
        lifecycle:
          postStart:
            exec:
              command: ["pip", "install", "transiter-nycsubway"]


---

apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.name }}-webservice
  labels:
    app: {{ .Values.name }}-webservice

spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: {{ .Values.name }}-webservice-pod
