name: Native host build and tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - name: Install Transiter and other Python packages
        run: |
          pip install --quiet .
          pip install --quiet -r dev-requirements.txt
      - name: Launch Postgres
        run: docker run -d --env POSTGRES_USER=transiter --env POSTGRES_PASSWORD=transiter --env POSTGRES_DB=transiter -p 5432:5432 postgres:12
      - name: Run unit tests
        run: coverage run --source=transiter --omit="transiter/alembic/*","*pb2/*" -m pytest --color=yes tests/unit tests/db
      # TODO
      # - name: Post coverage to Coveralls
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}

  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Transiter and other Python packages
        run: |
          pip install --quiet .
          pip install --quiet -r dev-requirements.txt
      - name: Launch Postgres, RabbitMQ, and Transiter services
        run: |
          docker run -d --env POSTGRES_USER=transiter --env POSTGRES_PASSWORD=transiter --env POSTGRES_DB=transiter -p 5432:5432 postgres:12
          docker run -d -p 5672:5672 rabbitmq:3
          transiterclt db reset --yes
          transiterclt launch webservice > webservice.log 2>&1 &
          transiterclt launch executor > executor.log 2>&1 &
          transiterclt launch scheduler > scheduler.log  2>&1 &
          python tests/endtoend/sourceserver.py > sourceserver.log  2>&1 &
      - name: Run end to end tests
        run: pytest --color=yes tests/endtoend

  database-upgrade-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Transiter and other Python packages
        run: |
          pip install --quiet .
      - name: Launch Postgres and restore the legacy database
        run: |
          docker run -d -v $(pwd)/tests/upgrade:/dumps --name postgres --env POSTGRES_USER=transiter --env POSTGRES_PASSWORD=transiter --env POSTGRES_DB=transiter -p 5432:5432 postgres:12
          sleep 10
          docker exec postgres pg_restore -U transiter -d transiter dumps/db.dump
      - name: Upgrade the database (this is the test)
        run: transiterclt db upgrade

  formatting-enforcement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Black and PyCodeStyle
        run: pip install --quiet black==19.10b pycodestyle==2.5.0
      - name: Run formatting checks
        run: |
          black transiter tests *py
          pycodestyle --ignore=E203,E501,W503 --exclude="*pb2.py" transiter tests *py
